<a href="https://colab.research.google.com/github/jnkx9c/CS-5390/blob/master/Pima_diabetes_mine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np
np.random.seed(7)




In [5]:
# load pima indians dataset
dataset = np.loadtxt("https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv", delimiter=",")
print(dataset.shape)

(768, 9)


In [0]:
XTRAIN = dataset[:700,0:8]
YTRAIN = dataset[:700,8]
XVALIDATION = dataset[700:,0:8]
YVALIDATION = dataset[700:,8]

In [7]:
print(XTRAIN.shape)
print(YTRAIN.shape)
print(XVALIDATION.shape)
print(YVALIDATION.shape)
print(XTRAIN[0:3,])
print(YTRAIN[0:3])
print(XVALIDATION[0:3,])
print(YVALIDATION[0:3])

(700, 8)
(700,)
(68, 8)
(68,)
[[  6.    148.     72.     35.      0.     33.6     0.627  50.   ]
 [  1.     85.     66.     29.      0.     26.6     0.351  31.   ]
 [  8.    183.     64.      0.      0.     23.3     0.672  32.   ]]
[1. 0. 1.]
[[  2.    122.     76.     27.    200.     35.9     0.483  26.   ]
 [  6.    125.     78.     31.      0.     27.6     0.565  49.   ]
 [  1.    168.     88.     29.      0.     35.      0.905  52.   ]]
[0. 1. 1.]


In [8]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
print(model.summary())

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 12)                108       
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 221
Trainable params: 221
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
model.fit(XTRAIN, YTRAIN, epochs=15, batch_size=10, validation_data=[XVALIDATION,YVALIDATION])

Train on 700 samples, validate on 68 samples
Epoch 1/15
700/700 [==============================] - 0s 133us/step - loss: 0.5147 - acc: 0.7614 - val_loss: 0.5468 - val_acc: 0.7500
Epoch 2/15
700/700 [==============================] - 0s 132us/step - loss: 0.5154 - acc: 0.7486 - val_loss: 0.5357 - val_acc: 0.7941
Epoch 3/15
700/700 [==============================] - 0s 134us/step - loss: 0.5190 - acc: 0.7486 - val_loss: 0.6045 - val_acc: 0.6765
Epoch 4/15
700/700 [==============================] - 0s 108us/step - loss: 0.5064 - acc: 0.7500 - val_loss: 0.5852 - val_acc: 0.7206
Epoch 5/15
700/700 [==============================] - 0s 107us/step - loss: 0.5287 - acc: 0.7329 - val_loss: 0.6126 - val_acc: 0.6912
Epoch 6/15
700/700 [==============================] - 0s 115us/step - loss: 0.5079 - acc: 0.7643 - val_loss: 0.6013 - val_acc: 0.6912
Epoch 7/15
700/700 [==============================] - 0s 112us/step - loss: 0.5149 - acc: 0.7486 - val_loss: 0.5729 - val_acc: 0.7206
Epoch 8/15
700/70

In [23]:

scores = model.evaluate(XTRAIN, YTRAIN)
print(model.metrics_names)
print(scores)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

700/700 [==============================] - 0s 29us/step
['loss', 'acc']
[0.4894465105874198, 0.7657142867360797]

acc: 76.57%


In [24]:
scores = model.evaluate(XVALIDATION, YVALIDATION)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

68/68 [==============================] - 0s 79us/step

acc: 77.94%


In [27]:
print(XVALIDATION[0:5])
print(YVALIDATION[0:10])

[[2.00e+00 1.22e+02 7.60e+01 2.70e+01 2.00e+02 3.59e+01 4.83e-01 2.60e+01]
 [6.00e+00 1.25e+02 7.80e+01 3.10e+01 0.00e+00 2.76e+01 5.65e-01 4.90e+01]
 [1.00e+00 1.68e+02 8.80e+01 2.90e+01 0.00e+00 3.50e+01 9.05e-01 5.20e+01]
 [2.00e+00 1.29e+02 0.00e+00 0.00e+00 0.00e+00 3.85e+01 3.04e-01 4.10e+01]
 [4.00e+00 1.10e+02 7.60e+01 2.00e+01 1.00e+02 2.84e+01 1.18e-01 2.70e+01]]
[0. 1. 1. 0. 0. 0. 1. 0. 1. 1.]


In [28]:
prediction = model.predict(XVALIDATION)
print(prediction[0:10].round())

[[0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]]


In [29]:
accuracy = accuracy_score(YVALIDATION, prediction.round())
precision = precision_score(YVALIDATION, prediction.round())
recall = recall_score(YVALIDATION, prediction.round())
f1score = f1_score(YVALIDATION, prediction.round())
print("Accuracy: %.2f%%" % (accuracy * 100.0))
print("Precision: %.2f%%" % (precision * 100.0))
print("Recall: %.2f%%" % (recall * 100.0))
print("F1-score: %.2f" % (f1score))

Accuracy: 77.94%
Precision: 80.00%
Recall: 59.26%
F1-score: 0.68
